# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/describe.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'proto/describe.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proto/describe.proto\x12\x04vlog\"6\n\x07Segment\x12\x14\n\x0cin_timestamp\x18\x01 \x01(\t\x12\x15\n\rout_timestamp\x18\x02 \x01(\t\"\xc5\x03\n\x10VideoDescription\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x1e\n\x16video_description_long\x18\x02 \x01(\t\x12\x1f\n\x17video_description_short\x18\x03 \x01(\t\x12\x19\n\x11primary_shot_type\x18\x04 \x01(\t\x12\x0c\n\x04tags\x18\x05 \x03(\t\x12\x14\n\x0clast_updated\x18\x06 \x01(\t\x12#\n\x1b\x63lassification_time_seconds\x18\x07 \x01(\x01\x12\x1c\n\x14\x63lassification_model\x18\x08 \x01(\t\x12\x1c\n\x14video_length_seconds\x18\t \x01(\x01\x12\x17\n\x0fvideo_timestamp\x18\n \x01(\t\x12\x1e\n\x16video_thumbnail_base64\x18\x0b \x01(\t\x12\x19\n\x11\x63lip_cut_duration\x18\x0c \x01(\x01\x12\x0c\n\x04keep\x18\r \x01(\x05\x12\x14\n\x0cin_timestamp\x18\x0e \x01(\t\x12\x15\n\rout_timestamp\x18\x0f \x01(\t\x12\x0e\n\x06rating\x18\x10 \x01(\x01\x12\x1f\n\x08segments\x18\x11 \x03(\x0b\x32\r.vlog.SegmentB\x08Z\x06vlogpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.describe_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\006vlogpb'
  _globals['_SEGMENT']._serialized_start=30
  _globals['_SEGMENT']._serialized_end=84
  _globals['_VIDEODESCRIPTION']._serialized_start=87
  _globals['_VIDEODESCRIPTION']._serialized_end=540
# @@protoc_insertion_point(module_scope)
