# resolve_clip_importer.py
#
# INSTRUCTIONS:
# 1. Place this file and 'clip_data.json' in the same directory.
# 2. IMPORTANT: Run this script from the DaVinci Resolve application's built-in Python console,
#    or from an external Python environment configured to access the Resolve API.

import json
import os
import re

# --- Configuration ---
JSON_FILE_PATH = "YOUR_FILE_PATH_HERE/clip_data.json"  # Path to the JSON file generated by db_extract.py
PROJECT_NAME = "Automated Timeline Setup"
PROJECT_FPS = 60.0  # Set this to your project's frame rate (e.g., 24.0, 25.0, 29.97, 30.0)
# ---------------------

def timestamp_to_frames(timestamp_str, fps):
    """
    Converts a HH:MM:SS.sss timestamp string to a frame number based on FPS.
    """
    try:
        # Regex to parse HH:MM:SS.sss format
        match = re.match(r'(\d{2}):(\d{2}):(\d{2})\.(\d{3})', timestamp_str)
        if match:
            H, M, S, ms = map(int, match.groups())
            total_seconds = H * 3600 + M * 60 + S + ms / 1000.0
        else:
            match = re.match(r'(\d{2}):(\d{2}):(\d{2})', timestamp_str)
            H, M, S  = map(int, match.groups())
            total_seconds = H * 3600 + M * 60 + S
            if not match:
                print(f"Error: Invalid timestamp format for '{timestamp_str}'. Expected HH:MM:SS.sss or HH:MM:SS")
                return -1

        
        # Round the result to the nearest whole frame for accuracy
        return int(round(total_seconds * fps))

    except Exception as e:
        print(f"Error converting timestamp '{timestamp_str}': {e}")
        return -1

def run_resolve_script():
    """
    The main function to execute the Resolve API workflow.
    """
    # 1. Access the DaVinci Resolve application object
    try:
        # This is the standard way to access the Resolve object in the scripting environment
        resolve = app.GetResolve()
    except Exception as e:
        print(f"Error: Could not access DaVinci Resolve application. Check your environment setup.")
        print(f"Details: {e}")
        return

    if not resolve:
        print("Error: DaVinci Resolve object is null.")
        return

    # 2. Load the clip data from JSON
    print(f"Loading data from: {os.path.abspath(JSON_FILE_PATH)}")
    if not os.path.exists(JSON_FILE_PATH):
        print(f"FATAL ERROR: JSON file not found at '{JSON_FILE_PATH}'. Please ensure it exists.")
        return

    try:
        with open(JSON_FILE_PATH, 'r') as f:
            data = json.load(f)
    except json.JSONDecodeError:
        print(f"FATAL ERROR: Could not decode JSON from '{JSON_FILE_PATH}'. Check file syntax.")
        return
    except Exception as e:
        print(f"FATAL ERROR reading JSON file: {e}")
        return


    project_manager = resolve.GetProjectManager()
    if not project_manager:
        print("Error: Could not get Project Manager.")
        return

    project = project_manager.GetCurrentProject()
            
    # Set the desired project frame rate for accurate frame calculation
    project.SetSetting("timelineFrameRate", str(PROJECT_FPS))
    print(f"Project '{PROJECT_NAME}' opened/created and project frame rate set to {PROJECT_FPS} FPS.")

    # 4. Access the Media Pool and prepare file list
    media_pool = project.GetMediaPool()
    if not media_pool:
        print("Error: Could not get Media Pool.")
        project_manager.CloseProject(project)
        return

    # Separate existing files from missing files
    file_paths_to_import = []
    clip_map = {} # Map full path to clip data for later processing

    for clip in data:
        full_path = clip["full_filepath"]
        if os.path.exists(full_path):
            file_paths_to_import.append(full_path)
            clip_map[full_path] = clip
        else:
            print(f"WARNING: File not found: {full_path}. Skipping import.")

    if not file_paths_to_import:
        print("Error: No existing files found to import after checking paths. Exiting.")
        project_manager.CloseProject(project)
        return

    # 5. Import the clips
    print(f"Attempting to import {len(file_paths_to_import)} existing files...")
    imported_items = media_pool.ImportMedia(file_paths_to_import)

    if not imported_items:
        print("FATAL ERROR: Resolve failed to import media files.")
        project_manager.CloseProject(project)
        return
    
    print(f"Successfully imported {len(imported_items)} items:")

    # Map imported Media Pool Item objects to their full file path for easy lookup
    item_map = dict()
    for item in imported_items:
        full_path = item.GetClipProperty("File Path")
        clip_data = clip_map[full_path]
        item_map[full_path] = (item, clip_data)

    print("Create empty timeline")
    media_pool.CreateEmptyTimeline("timeline")

    print("Applying metadata (Clip In/Out, Short Name) to imported clips...")
    
    processed_count = 0
    sorted_clips = []
    for full_path in sorted(item_map):
        media_pool_item, clip_data = item_map[full_path]

        sorted_clips.append(media_pool_item)
        print('media path: ', full_path)
        print('media_pool_item: ', media_pool_item)
        in_ts = clip_data["in_timestamp"]
        out_ts = clip_data["out_timestamp"]
        short_name = clip_data["video_description_short"]

        # Convert timestamps to frames
        in_frame = timestamp_to_frames(in_ts, PROJECT_FPS)
        out_frame = timestamp_to_frames(out_ts, PROJECT_FPS)

        if in_frame == -1 or out_frame == -1:
            print(f"Skipping '{short_name}' due to timestamp conversion error.")
            continue

        # Set Clip Properties (Resolve requires frame numbers as strings)
        print(media_pool_item.GetName())
        print(media_pool_item.GetMarkInOut())
        print(media_pool_item.GetClipProperty())
        media_pool_item.SetClipProperty("Clip Name", short_name)
        media_pool_item.SetMarkInOut(in_frame, out_frame, type=all)
        print('Appending to timeline: ', media_pool.AppendToTimeline(media_pool_item))
        processed_count += 1

        print(f"-> Set: '{short_name}' | In: {in_ts} | Out: {out_ts}")


    print(f"\n--- Script Complete ---")
    print(f"Total Clips Processed: {processed_count}")
    print(f"Project '{PROJECT_NAME}' is ready in DaVinci Resolve.")

if __name__ == "__main__":
    run_resolve_script()
